name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PVT_KEY }}
        script: |
          cd nifty-tales
          sudo git pull
          sudo npm i
          sudo PORT=3003 npm run build
          sudo pm2 restart nifty-tales
