name: Sync to Contabo Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PVT_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Sync repository
      env:
        HOST: ${{ secrets.SERVER_HOST }}
        USER: ${{ secrets.SERVER_USER }}
        TARGET: ${{ secrets.SERVER_PATH }}
      run: |
        rsync -avz --delete ./ $USER@$HOST:$TARGET

    - name: Restart PM2 process
      env:
        HOST: ${{ secrets.SERVER_HOST }}
        USER: ${{ secrets.SERVER_USER }}
      run: |
        ssh $USER@$HOST "cd ${{ secrets.SERVER_TARGET }} && \
        npm i && \
        PORT=3003 npm run build && \
        pm2 restart 6"