name: The Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_PVT_KEY }}
          script: |
            cd nifty-tales
            echo $(whoami) is now in $(pwd)
            git pull
            npm install
            npm run build
            pm2 restart nifty-tales