name: The Deployment Workflow 4

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change directory
        run: | 
          echo $(pwd)
          cd ~/nifty-tales
          echo $(pwd)

      - name: Git Pull
        run: git pull
      
      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build
      
      - name: Restart pm2
        run: pm2 restart nifty-tales